name: Conjecture Games
url: http://conjecturegames.com/
credit: Zach Best
desc: CRGE, BOLD, UNE

generators:
  - connection
  - loom
  - npc_creator
  - npc_interaction
  - waylay
  - waylay_arced
attribution: |
  <h5>CRGE, Conjectural Roleplaying GM Emulator</h5>
  All text is © Zach Best (2014).
  <br/><a href="http://www.drivethrurpg.com/product/145426/CRGE-Conjectural-Roleplaying-GM-Emulator">CRGE on DriveThruRPG</a>
  <blockquote>
  <p>CRGE is a GM emulator that works on adding the unexpected to your imagination. CRGE is a
  tiered system to create a role-playing experience without a GM. At the base level the system
  works to answer "yes or no" questions while constantly pushing the game towards the unexpected.
  At the intermediate level, the system weaves story threads together to give each scene a focus
  in advancing a specific narrative. At the high level, CRGE provides frameworks to tell complete
  stories by yourself, with a group of friends, or even online.</p>
  </blockquote>

  <h5>UNE, The Universal NPC Emulator</h5>
  All text is © Zach Best (2007, 2014).
  <br/><a href="http://www.drivethrurpg.com/product/134163/UNE-The-Universal-NPC-Emulator-rev">UNE on DriveThruRPG</a>
  <blockquote>
  <p>UNE is the Universal NPC Emulator. With just a handful of dice rolls, UNE can help create a
  surprising non-player character (NPC) with its own motivations. A few more dice rolls, and UNE
  can provide more direction to place the newly-created NPC smack dab in the center of the story.
  It can even help determine the NPC’s general mood towards the player characters.</p>
  </blockquote>

  <h5>BOLD, Universal PC Stories and Deeds Generator</h5>
  All text is © Zach Best (2014).
  <br/><a href="http://www.drivethrurpg.com/product/137746/BOLD-Universal-PC-Stories-and-Deeds-Generator">BOLD on DriveThruRPG</a>
  <blockquote>
  <p>BOLD is the book of legends and deeds. With just a handful of dice rolls, BOLD can generate
  interesting character histories, downtime events, and even adventures. Any character instantly
  obtains deeds and legends that are overcome in unexpected ways. These deeds can even arc out
  in to entire stories.</p>
  </blockquote>

