name: Conjecture Games
id: conjecture_games
icon: cmd-book-open-page-variant
url: http://conjecturegames.com/
credit: Zach Best
attribution: |
  <h5>UNE, The Universal NPC Emulator</h5>
  All text is © Zach Best (2007, 2014).
  http://www.drivethrurpg.com/product/134163/UNE-The-Universal-NPC-Emulator-rev
  <blockquote>
  <p>UNE is the Universal NPC Emulator. With just a handful of dice rolls, UNE can help create a
  surprising non-player character (NPC) with its own motivations. A few more dice rolls, and UNE
  can provide more direction to place the newly-created NPC smack dab in the center of the story.
  It can even help determine the NPC’s general mood towards the player characters.

  <br/>Best of all UNE is system and setting agnostic. It will work in Techno-Roman science
  fiction just as well as 1930′s Cthulhu hour or apocalypse fantasy.</p>
  </blockquote>

