name: The Fourth Page
id: fourth_page
priority: 200
credit: Mike Riverso
icon: cmd-numeric-4-box-outline
attribution: |
  <p><cite>the Fourth Page</cite> generators for World of Dungeons.
  <br/>
  <br/>Licensed under the Creative Commons Attribution 3.0 Unported License. To view a copy
  of this license, visit https://creativecommons.org/licenses/by/3.0/
  </p>
