name: Roll XX
id: roll_xx
priority: 100
url: http://www.drivethrurpg.com/product/108917/Roll-XX
credit: The Sentinels of Meregoth / Neoplastic Press
hasGroupHierarchy: true
groups:
  grpFantNPCs: Fantasy / NPCs
  grpFantAdvSeed: Fantasy / Adventure Seeds
  grpFantChars: Fantasy / Characters
  grpFantMonsters: Fantasy / Monsters
  grpFantMagic: Fantasy / Magic
  grpFantSettings: Fantasy / Settings
  grpSuperHeroes: Superheroes / Heroes
  grpSuperVillains: Superheroes / Villains
  grpSuperAdvSeed: Superheroes / Adventure Seeds
  grpSciFiShip: Science Fiction / Starships
  grpSciFiAdvSeed: Science Fiction / Adventure Seeds
  grpHorrorChars: Horror / Characters
  grpHorrorMonsters: Horror / Monsters
  grpHorrorSettings: Horror / Settings
  grpHorrorAdvSeeds: Horror / Adventure Seeds
  grpModernChars: Modern / Characters
  grpModernSettings: Modern / Settings
  grpModernAdvSeeds: Modern / Adventure Seeds
attribution: |
  <blockquote>
  <p>Roll XX is a system-agnostic book of random tables for fantasy, sci-fi, superheroes, and horror role-playing games.
  <br/>Packed with adventure hooks, story seeds, NPCs, magic items, spaceships, demons, and locations, Roll XX features 90 questions and 1800 answers.
  <br/>And it's open-source!</p>
  <p>
  Roll XX: Double Damage is a book of random tables for fantasy role-playing games. Packed with adventure seeds, dungeon encounters, NPCs, magic items, treasure, and locations, Roll XX features 20 questions and 450 answers.
  <br/>It also includes an ugly-as-sin monster generator in the back with over 10,000,000,000 murderous combinations.
  <br/>And it's open-source!
  </p>
  <p>http://www.drivethrurpg.com/product/113448/Roll-XX-Double-Damage</p>
  </blockquote>
