name: Roll XX
id: roll_xx
url: http://www.drivethrurpg.com/browse/pub/2623/Neoplastic-Press
credit: The Sentinels of Meregoth / Neoplastic Press
hasGroupHierarchy: true
icon: cmd-format-superscript

groupedGenerators:
  grpFantAdvSeed:
  - fant_assassins
  - fant_hirer
  - fant_searching
  - fant_stole_blade
  - fant_time_period
  - fant_where_going
  grpFantCityDressing:
  - fant_banquet
  - fant_bird_beak
  - fant_guard
  - fant_medical_procedure
  - fant_shopkeeper
  - fant_sky
  grpFantDungeonDressing:
  - fant_dungeon
  - fant_locked_door
  - fant_sepulchre
  - fant_sprung_trap
  - fant_treasure_seeker
  - fant_wall_runes
  grpFantChars:
  - fant_barbarian
  - fant_believe
  - fant_cleric
  - fant_dark_secret
  - fant_mage_truth
  - fant_oath
  grpFantNPCs:
  - fant_elves
  - fant_frost_dragon
  - fant_orc_chieftan
  - fant_queen
  - fant_rider
  - fant_warrior_armor
  grpFantMagic:
  - fant_miscast_spell
  - fant_necromancer
  - fant_potion
  - fant_sorcerors
  - fant_summoned
  - fant_wand
  grpFantMonsters:
  - fant_monster_gen #0
  - fant_new_threat #0
  - fant_automaton
  - fant_blob
  - fant_hybrid
  - fant_demon_from #2000
  - fant_demon_kind #2000
  grpFantTreasure:
  - fant_dragon
  - fant_enchanted_jewelry
  - fant_obelisk
  - fant_search_corpse
  - fant_treasure_chest


  grpHorrorAdvSeeds:
  - horror_bodies_hidden
  - horror_clue
  - horror_cure
  - horror_signature
  - horror_soul
  - horror_zombie_story
  grpHorrorChars:
  - horror_familiar
  - horror_love
  - horror_make_it_stop
  - horror_memories
  - horror_scars
  - horror_under_skin
  - horror_vices
  grpHorrorMonsters:
  - horror_bites
  - horror_crypt
  - horror_escape
  - horror_monster_type
  - horror_they
  - horror_unseen_entity
  grpHorrorSights:
  - horror_body_part
  - horror_ceiling
  - horror_crime_scene
  - horror_hole
  - horror_shadow
  - horror_under_bed
  grpHorrorSounds:
  - horror_noise
  - horror_sound


  grpModernChars:
  - modern_callsign
  - modern_expertise
  - modern_fingerprints
  - modern_secret
  - modern_secret_society
  - modern_sentry
  grpModernMissions:
  - modern_duffel
  - modern_primary_objective
  - modern_suitcase
  - modern_tonight
  grpModernRoomDressing:
  - modern_insects
  - modern_liquid
  - modern_magic
  - modern_pool
  - modern_smell
  - modern_vehicle

  grpSciFiAdvSeed:
  - scifi_ancient_terminal
  - scifi_anomaly
  - scifi_bounty_hunter
  - scifi_escape
  - scifi_rubble
  - scifi_xenomorph
  grpSciFiShip:
  - scifi_land
  - scifi_malfunction
  - scifi_passengers
  - scifi_starship_type
  - scifi_went_dark

  grpSuperAdvSeed:
  - supers_aliens
  - supers_connections
  - supers_protecting
  grpSuperHeroes:
  - supers_origin
  - supers_useless_power
  - supers_weakness
  - supers_who_the_heck
  grpSuperVillains:
  - supers_villain_lair
  - supers_villain_rant
  - supers_villain_target
  - supers_villain_threat

groups:
- name: fantasy
  uiName: Fantasy
  icon: cmd-castle
  groups:
  - name: grpFantAdvSeed
    uiName: Adventure Seeds
    icon: cmd-sword
  - name: grpFantCityDressing
    uiName: City Dressing
    icon: cmd-castle
  - name: grpFantDungeonDressing
    uiName: Dungeon Dressing
    icon: cmd-cube-unfolded
  - name: grpFantChars
    uiName: Characters
    icon: cmd-account
  - name: grpFantNPCs
    uiName: NPCs
    icon: cmd-account-multiple
  - name: grpFantMagic
    uiName: Magic
    icon: cmd-auto-fix
  - name: grpFantMonsters
    uiName: Monsters
    icon: cmd-paw
  - name: grpFantTreasure
    uiName: Treasure & Items
    icon: cmd-diamond
- name: horror
  uiName: Horror
  icon: cmd-ghost
  groups:
  - name: grpHorrorAdvSeeds
    uiName: Adventure Seeds
    icon: ion-bonfire
  - name: grpHorrorChars
    uiName: Characters
    icon: cmd-emoticon-devil
  - name: grpHorrorMonsters
    uiName: Monsters
    icon: cmd-duck
  - name: grpHorrorSights
    uiName: Sights
    icon: cmd-face
  - name: grpHorrorSounds
    uiName: Sounds
    icon: cmd-face-profile
- name: modern
  uiName: Modern
  icon: cmd-city
  groups:
  - name: grpModernChars
    uiName: Characters
    icon: cmd-account
  - name: grpModernMissions
    uiName: Missions
    icon: cmd-puzzle
  - name: grpModernRoomDressing
    uiName: Room Dressing
    icon: cmd-domain
- name: scifi
  uiName: Science Fiction
  icon: ion-planet
  groups:
  - name: grpSciFiAdvSeed
    uiName: Adventure Seeds
    icon: cmd-robot
  - name: grpSciFiShip
    uiName: Starships
    icon: cmd-rocket
- name: superheroes
  uiName: Superheroes
  icon: cmd-dna
  groups:
  - name: grpSuperAdvSeed
    uiName: Adventure Seeds
    icon: cmd-bomb
  - name: grpSuperHeroes
    uiName: Heroes
    icon: cmd-emoticon
  - name: grpSuperVillains
    uiName: Villains
    icon: cmd-emoticon-devil

attribution: |
  <p><a href="http://www.drivethrurpg.com/product/108917/Roll-XX">Roll XX on DriveThruRPG</a></p>
  <p>
  <em>
  To game designers: <cite>Roll XX</cite> is an open-source game sourcebook,
  meaning that you have our permission to use the contents to
  create other commercial works -- there is no need to solicit our
  permission. Do as thou wilt! All we ask is that you kindly credit
  <cite>The Sentinels of Meregoth</cite> somewhere in the text.
  </em>
  </p>
  <blockquote>
  <p>Roll XX is a system-agnostic book of random tables for fantasy, sci-fi, superheroes, and horror role-playing games.
  <br/>Packed with adventure hooks, story seeds, NPCs, magic items, spaceships, demons, and locations, Roll XX features 90 questions and 1800 answers.
  <br/>And it's open-source!</p>
  </blockquote>
  <p><a href="http://www.drivethrurpg.com/product/113448/Roll-XX-Double-Damage">Roll XX: Double Damage on DriveThruRPG</a></p>
  <blockquote>
  <p>
  Roll XX: Double Damage is a book of random tables for fantasy role-playing games. Packed with adventure seeds, dungeon encounters, NPCs, magic items, treasure, and locations, Roll XX features 20 questions and 450 answers.
  <br/>It also includes an ugly-as-sin monster generator in the back with over 10,000,000,000 murderous combinations.
  <br/>And it's open-source!
  </p>
  </blockquote>
