name: Roll XX
id: roll_xx
url: http://www.drivethrurpg.com/browse/pub/2623/Neoplastic-Press
credit: The Sentinels of Meregoth / Neoplastic Press
hasGroupHierarchy: true
icon: cmd-format-superscript
groupIcons:
  Fantasy: cmd-castle
  grpFantAdvSeed: cmd-sword
  grpFantCityDressing: cmd-castle
  grpFantDungeonDressing: cmd-cube-unfolded
  grpFantChars: cmd-account
  grpFantNPCs: cmd-account-multiple
  grpFantMagic: cmd-auto-fix
  grpFantMonsters: cmd-paw
  grpFantTreasure: cmd-diamond

  Horror: cmd-ghost
  grpHorrorAdvSeeds: ion-bonfire
  grpHorrorChars: cmd-emoticon-devil
  grpHorrorMonsters: cmd-duck
  grpHorrorSights: cmd-face
  grpHorrorSounds: cmd-face-profile

  Modern: cmd-city
  grpModernChars: cmd-account
  grpModernMissions: cmd-puzzle
  grpModernRoomDressing: cmd-domain

  Science Fiction: ion-planet
  grpSciFiAdvSeed: cmd-robot
  grpSciFiShip: cmd-rocket

  Superheroes: cmd-dna
  grpSuperAdvSeed: cmd-bomb
  grpSuperHeroes: cmd-emoticon
  grpSuperVillains: cmd-emoticon-devil
groups:
  grpFantAdvSeed: Fantasy / Adventure Seeds
  grpFantCityDressing: Fantasy / City Dressing
  grpFantDungeonDressing: Fantasy / Dungeon Dressing
  grpFantChars: Fantasy / Characters
  grpFantNPCs: Fantasy / NPCs
  grpFantMagic: Fantasy / Magic
  grpFantMonsters: Fantasy / Monsters
  grpFantTreasure: Fantasy / Treasure & Items

  grpHorrorAdvSeeds: Horror / Adventure Seeds
  grpHorrorChars: Horror / Characters
  grpHorrorMonsters: Horror / Monsters
  grpHorrorSights: Horror / Sights
  grpHorrorSounds: Horror / Sounds

  grpModernChars: Modern / Characters
  grpModernMissions: Modern / Missions
  grpModernRoomDressing: Modern / Room Dressing

  grpSciFiAdvSeed: Science Fiction / Adventure Seeds
  grpSciFiShip: Science Fiction / Starships

  grpSuperAdvSeed: Superheroes / Adventure Seeds
  grpSuperHeroes: Superheroes / Heroes
  grpSuperVillains: Superheroes / Villains
attribution: |
  <blockquote>
  <p>Roll XX is a system-agnostic book of random tables for fantasy, sci-fi, superheroes, and horror role-playing games.
  <br/>Packed with adventure hooks, story seeds, NPCs, magic items, spaceships, demons, and locations, Roll XX features 90 questions and 1800 answers.
  <br/>And it's open-source!</p>
  <p><a href="http://www.drivethrurpg.com/product/108917/Roll-XX">Roll XX on DriveThruRPG</a></p>
  </blockquote>
  <blockquote>
  <p>
  Roll XX: Double Damage is a book of random tables for fantasy role-playing games. Packed with adventure seeds, dungeon encounters, NPCs, magic items, treasure, and locations, Roll XX features 20 questions and 450 answers.
  <br/>It also includes an ugly-as-sin monster generator in the back with over 10,000,000,000 murderous combinations.
  <br/>And it's open-source!
  </p>
  <p><a href="http://www.drivethrurpg.com/product/113448/Roll-XX-Double-Damage">Roll XX: Double Damage on DriveThruRPG</a></p>
  </blockquote>
