title: Adventuresmith
description: Generate tabletop RPG nonsense at the push of a button! (on Android)
google_analytics: 
show_downloads: true
theme: jekyll-theme-time-machine

gems:
  - jekyll-mentions
