name: Zenopus Archives
id: zenopus_archives
url: http://zenopusarchives.blogspot.com/
credit: Zenopus Archives
icon: cmd-cube
attribution: |
  Zenopus Archives blog is at http://zenopusarchives.blogspot.com/
  <p>Reference Sheets for Holmes Basic Referees: https://sites.google.com/site/zenopusarchives/home/holmes-ref</p>
  <blockquote>
  In 1977, TSR published the first introductory set for Dungeons & Dragons. This Basic Set
  included a monochrome blue rulebook (the Blue Book) edited by Dr. J. Eric Holmes from the
  original D&D booklets (the Little Brown Books) by Gary Gygax and Dave Arneson, and the first
  supplements. Holmes also created a Sample Dungeon for the rulebook in which novice adventurers
  from Portown explore the dungeon beneath the ruined tower of the wizard Zenopus.
  This set served its role ably until 1981 when it was replaced by a revised Basic Set.
  Some still find Holmes Basic, as the rules are popularly known, to be a concise 48-page
  introduction to OD&D or AD&D, and others have been inspired to use it as the basis for
  expansion to an entire game of its own. Many gamers involved in the current
  "Old School Renaissance" (OSR) started with the Holmes Set.
  </blockquote>


