name: The Perilous Wilds
id: perilous_wilds
credit: Jason Lutes
url: "http://www.drivethrurpg.com/product/156979/The-Perilous-Wilds"
icon: cmd-image-filter-hdr
groupIcons:
  grp1: cmd-magnify
  grp2: cmd-book-open-page-variant
  grp3: ion-ios-paw
  grp4: cmd-account-multiple
  grp5: cmd-white-balance-iridescent
groups:
  grp1: Dangers & Discoveries
  grp2: Create & Name
  grp3: Creatures
  grp4: NPCs
  grp5: Treasure
attribution: |
  <p>http://lampblackandbrimstone.blogspot.com/</p>
  <p>Written by <strong>Jason Lutes</strong> in Hartland, Vermont, U.S.A. with assistance from <strong>Jeremy Strandberg</strong> in Madison, Wisconsin, U.S.A.</p>
  <p>The contents of this supplement rely upon the rules contained in <em>Dungeon World</em>, by <strong>Adam Koebel</strong> and <strong>Sage LaTorra</strong>,
  licensed under a Creative Commons Attribution 3.0 Unported license</p>
  <p>The text of The <em>Perilous Wilds</em> is released under a Creative Commons Attribution - ShareAlike 3.0 Unported license.</p>

