name: The Perilous Wilds
id: perilous_wilds
credit: Jason Lutes
url: "http://www.drivethrurpg.com/product/156979/The-Perilous-Wilds"
icon: cmd-image-filter-hdr

groupedGenerators:
  dang_disc:
  - danger
  - discovery
  - explore_dungeon
  create_name:
  - dungeon #100
  - steading
  - follower #200

  - place_names
  - region_names

  - names_arpad #2000
  - names_oloru #2000
  - names_tamanarugan #2000
  - names_valkoina
  creatures:
  - creature #100
  - creature_beast
  - creature_human
  - creature_humanoid
  - creature_monster
  npcs:
  - npc #100
  - npc_rural
  - npc_urban
  - npc_wilderness
  treasure:
  - treasure_unguarded
  - treasure_item #100
  - treasure_guarded
groups:
- name: dang_disc
  uiName: Dangers & Discoveries
  icon: cmd-magnify
- name: create_name
  uiName: Create & Name
  icon: cmd-book-open-page-variant
- name: creatures
  uiName: Creatures
  icon: ion-ios-paw
- name: npcs
  uiName: NPCs
  icon: cmd-account-multiple
- name: treasure
  uiName: Treasure
  icon: cmd-white-balance-iridescent
attribution: |
  <p><a href="http://lampblackandbrimstone.blogspot.com/">Lampblack &amp; Brimstone</a></p>
  <p>Written by <strong>Jason Lutes</strong> in Hartland, Vermont, U.S.A. with assistance from <strong>Jeremy Strandberg</strong> in Madison, Wisconsin, U.S.A.</p>
  <p>The contents of this supplement rely upon the rules contained in <em>Dungeon World</em>, by <strong>Adam Koebel</strong> and <strong>Sage LaTorra</strong>,
  licensed under a Creative Commons Attribution 3.0 Unported license</p>
  <p>The text of The <em>Perilous Wilds</em> is released under a Creative Commons Attribution - ShareAlike 3.0 Unported license.</p>

