name: The Queen's Cavaliers
credit: Caoimhe Ora Snow
url: "http://www.boldpueblo.com/tqc"

groups:
- name: tqcChargen
  uiName: Character Creation
  icon: cmd-account-settings-variant
- name: tqcCalendar
  uiName: Dates and Calendars
  icon: cmd-calendar-clock
- name: tqcSetting
  uiName: Gallinea and the World
  icon: ion-earth
- name: tqcDiceRoller
  uiName: TQC Dice Rollers
  icon: cmd-dice-multiple

attribution: |
             <p><a href="http://boldpueblo.com/tqc">The Queen's Cavaliers</p>
             <p>Written by <b>Caoimhe Ora Snow</b></p>
             <p>Rule mechanics are released under a <a href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution License (CC BY 4.0)</a>, and the setting under a <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike License (CC BY-NC-SA 4.0)</a>.</p>
