name: Stonetop
id: stonetop
url: https://plus.google.com/collection/c0dRb
credit: Jeremy Strandberg
icon: cmd-barley
attribution: |
  Licensed under Creative Commons Attribution 3.0 Unported License.


