name: Misc. Generators
id: misc
priority: 900
credit: Various Authors
icon: cmd-dice-d20
attribution: |
  <p>The 'Misc' section includes generators that aren't part of any particular larger collection. (yet)</p>

  <h5>Joel Priddy</h5>
  Boiler Plate Fantasy playbooks http://abominablefancy.blogspot.com/2016/02/boilerplate-fantasy-playbooks.html
  <br/>Patron Deity generator is from the Cleric playbook.

  <h5>Jeremy Strandberg</h5>
  Stonetop https://plus.google.com/collection/c0dRb
  <br/>Minor Arcana generator
  <br/>Licensed under Creative Commons Attribution 3.0 Unported License.



