name: Misc. Generators
id: misc
priority: 900
credit: Various Authors
icon: cmd_hexagon_multiple
groups:
  grpChar: Characters
  grpGME: GM Emulators
  grpItems: Items
groupIcons:
  grpItems: cmd-engine
  grpChar: cmd-account
  grpGME: cmd-lightbulb-on-outline

attribution: |
  <p>The 'Misc' section includes generators that aren't part of any particular larger grouping. (yet)</p>

  <h5>Jeremy Strandberg</h5>
  <a href="https://plus.google.com/collection/c0dRb">Stonetop on G+</a>
  <h6>Minor Arcana generator</h6>
  <br/>Licensed under Creative Commons Attribution 3.0 Unported License. To view a copy
  of this license, visit https://creativecommons.org/licenses/by/3.0/

  <h5>Joel Priddy</h5>
  <a href="http://abominablefancy.blogspot.com/">Joel Priddy's blog</a>
  <h6>Patron Deity Generator</h6>
  <p>© Joel Priddy 2016</p>
  The Patron Deity generator is from the Cleric playbook in Joel's
  <a href="http://abominablefancy.blogspot.com/2016/02/boilerplate-fantasy-playbooks.html">Boiler Plate Fantasy playbooks</a>
  <h6>Dungeon Cocktail</h6>
  <p>© Joel Priddy 2017</p>
  <a href="http://abominablefancy.blogspot.com/2017/04/mini-game-potion-quaffing.html">Mini-game: Potion Quaffing</a>

  <h5>Sophia Brandt</h5>
  <p><a href="http://dieheart.net/">Sophia's blog</a> is full great resources (reviews, actual plays, resource lists) for
  Dungeon World, The Black Hack, solo RPGs, and much more.
  <br/>
  <br/>The content of Sophia's blog is licensed under a Creative Commons Attribution 4.0 International License.
   To view a copy of this license, visit http://creativecommons.org/licenses/by/4.0/
  </p>

  <h6>Tiny Universal Engine</h6>
  <a href="http://dieheart.net/tiny-universal/">Tiny Universal Engine</a>


  <h5>Zenopus Archives</h5>
  <p>
  <a href="http://zenopusarchives.blogspot.com/">Zenopus Archives blog</a>
  <br/><a href="https://sites.google.com/site/zenopusarchives/home/holmes-ref">Reference Sheets for Holmes Basic Referees</a> </p>
  <blockquote>
  In 1977, TSR published the first introductory set for Dungeons & Dragons. This Basic Set
  included a monochrome blue rulebook (the Blue Book) edited by Dr. J. Eric Holmes from the
  original D&D booklets (the Little Brown Books) by Gary Gygax and Dave Arneson, and the first
  supplements. Holmes also created a Sample Dungeon for the rulebook in which novice adventurers
  from Portown explore the dungeon beneath the ruined tower of the wizard Zenopus.
  This set served its role ably until 1981 when it was replaced by a revised Basic Set.
  Some still find Holmes Basic, as the rules are popularly known, to be a concise 48-page
  introduction to OD&D or AD&D, and others have been inspired to use it as the basis for
  expansion to an entire game of its own. Many gamers involved in the current
  "Old School Renaissance" (OSR) started with the Holmes Set.
  </blockquote>


