name: Misc. Generators
id: misc
priority: 900
credit: Various Authors
icon: cmd_hexagon_multiple
groups:
  grpChar: Characters
  grpGME: GM Emulators
  grpItems: Items
  grp4th: The Fourth Page
groupIcons:
  grp4th: cmd-numeric-4-box-outline
  grpItems: cmd-engine
  grpChar: cmd-account
  grpGME: cmd-lightbulb-on

attribution: |
  <p>The 'Misc' section includes generators that aren't part of any particular larger grouping. (yet)</p>

  <h5>Joel Priddy</h5>
  Boiler Plate Fantasy playbooks http://abominablefancy.blogspot.com/2016/02/boilerplate-fantasy-playbooks.html
  <br/>Patron Deity generator is from the Cleric playbook.

  <h5>Jeremy Strandberg</h5>
  Stonetop https://plus.google.com/collection/c0dRb
  <br/>Minor Arcana generator
  <br/>Licensed under Creative Commons Attribution 3.0 Unported License. To view a copy
  of this license, visit https://creativecommons.org/licenses/by/3.0/

  <h5>Mike Riverso</h5>
  <cite>the Fourth Page</cite> generators for World of Dungeons.
  <br/>
  <br/>Licensed under the Creative Commons Attribution 3.0 Unported License. To view a copy
  of this license, visit https://creativecommons.org/licenses/by/3.0/


  <h5>Zenopus Archives</h5>
  Zenopus Archives blog is at http://zenopusarchives.blogspot.com/
  <p>Reference Sheets for Holmes Basic Referees: https://sites.google.com/site/zenopusarchives/home/holmes-ref</p>
  <blockquote>
  In 1977, TSR published the first introductory set for Dungeons & Dragons. This Basic Set
  included a monochrome blue rulebook (the Blue Book) edited by Dr. J. Eric Holmes from the
  original D&D booklets (the Little Brown Books) by Gary Gygax and Dave Arneson, and the first
  supplements. Holmes also created a Sample Dungeon for the rulebook in which novice adventurers
  from Portown explore the dungeon beneath the ruined tower of the wizard Zenopus.
  This set served its role ably until 1981 when it was replaced by a revised Basic Set.
  Some still find Holmes Basic, as the rules are popularly known, to be a concise 48-page
  introduction to OD&D or AD&D, and others have been inspired to use it as the basis for
  expansion to an entire game of its own. Many gamers involved in the current
  "Old School Renaissance" (OSR) started with the Holmes Set.
  </blockquote>

  <h5>Mythic Fate Chart Variant</h5>
  From this post: http://solodungeoneer.blogspot.com/2012/09/mythic-fate-chart-variant.html




