name: /r/BehindTheTables
id: behind_the_tables
url: https://www.reddit.com/r/BehindTheTables/
credit: /r/DnDBehindTheScreen
priority: 900
hasGroupHierarchy: true

groupedGenerators:
  grpEncountersCastle:
  - castle_encounters_dungeon
  - castle_encounters_peace
  - castle_encounters_siege
  grpEncountersDungeon:
  - encounters_dungeon #2000
  grpEncountersTown:
  - temple_encounter
  - encounters_idyllic_village #2000
  - encounters_rotting_city #2000
  grpEncountersWild:
  - monastery_encounter
  - prison_encounter
  - encounters_acient_forest #2000
  - encounters_ship_sea #2000
  grpFactionsSettlement:
  - assassin_guild
  - crafting_guild
  - cult
  - merchant_guild
  - noble_house
  - secret_society
  - trading_company
  - urban_gang
  - watchmen
  grpFactionsWild:
  - goblin_gang
  - mercenary_troop
  - military_company
  - orkish_clan
  - outlaw_band
  - pirate_crew
  - savage_horde
  grpLocationsCastle:
  - castle # 0
  - castle_room #0
  - castle_dungeon
  - castle_dungeon_room
  grpLocationsCavern:
  - mine #200
  - mine_explore #200
  - cavern_explore
  - caverns
  grpLocationsDungeon:
  - basic_dungeon
  - dungeon_dressing
  grpLocationsTown:
  - pub_names
  - temple
  - temple_explore
  - tomb
  - tomb_explore
  grpLocationsWild:
  - monastery #100
  - monastery_explore #100
  - prison # 200
  - prison_explore #200
  - mage_towers
  grpNPCsAppPersMotiv:
  - npc # 0
  - npc_appearance
  - npc_personality
  grpNPCsCastle:
  - c_archer
  - c_armorer
  - c_bowyer
  - c_cook
  - c_guard
  - c_guard_captain
  - c_horsemaster
  - c_huntsman
  - c_kennelmaster
  - c_stable_hand
  grpNPCsCastleCourt:
  - c_chaplain
  - c_fool
  - c_knight
  - c_nobleman
  - c_noblewoman
  - c_retainer
  - c_servant
  - c_steward
  - c_tutor
  grpNPCsCastleDungeon:
  - c_jailer
  - c_prisoner
  - c_torturer
  grpNPCsCavern:
  - dark_elf
  - dwarf
  - miner
  grpNPCsTown:
  - cultist
  - t_noble
  - t_priest
  - t_seer
  - t_traveler
  - temple_priest
  grpNPCsTownLaw:
  - constable
  - gang_member
  - t_criminal
  - t_law_official
  - watch_guard
  grpNPCsTownMerchant:
  - apprentice_crafter
  - artisan
  - assassin
  - merchant
  - shopkeeper
  - t_alchemist
  - t_server
  - t_smith
  grpNPCsWild:
  - barbarian
  - goblin
  - monk
  - orc
  - p_guard
  - p_jailer
  - p_prisoner
  - pirate
  - poacher
  - robber
  - sellsword
  - smuggler
  - soldier

groups:
  - name: encounters
    uiName: Encounters
    icon: cmd-run
    groups:
    - name: grpEncountersCastle
      uiName: Castle
      icon: cmd-castle
    - name: grpEncountersDungeon
      uiName: Dungeon
      icon: cmd-cube-unfolded
    - name: grpEncountersTown
      uiName: Town
      icon: cmd-home
    - name: grpEncountersWild
      uiName: Wildnerness
      icon: cmd-pine-tree
  - name: factions
    uiName: Factions & Groups
    icon: cmd-account-multiple
    groups:
    - name: grpFactionsSettlement
      uiName: Settlement
      icon: cmd-home
    - name: grpFactionsWild
      uiName: Wilderness
      icon: cmd-pine-tree
  - name: locations
    uiName: Locations
    icon: cmd-map-marker
    groups:
    - name: grpLocationsCastle
      uiName: Castle
      icon: cmd-castle
    - name: grpLocationsCavern
      uiName: Cavern
      icon: cmd-fire
    - name: grpLocationsDungeon
      uiName: Dungeon
      icon: cmd-cube-unfolded
    - name: grpLocationsTown
      uiName: Town
      icon: cmd-home
    - name: grpLocationsWild
      uiName: Wilderness
      icon: cmd-pine-tree
  - name: npcs
    uiName: NPCs
    icon: cmd-account
    groups:
    - name: grpNPCsAppPersMotiv
      uiName: Appearance, Motivations...
      icon: cmd-face
    - name: grpNPCsCastle
      uiName: Castle
      icon: cmd-castle
    - name: grpNPCsCastleCourt
      uiName: Castle Court
      icon: cmd-castle
    - name: grpNPCsCastleDungeon
      uiName: Dungeon
      icon: cmd-castle
    - name: grpNPCsCavern
      uiName: Cavern
      icon: cmd-fire
    - name: grpNPCsTown
      uiName: Town
      icon: cmd-home
    - name: grpNPCsTownLaw
      uiName: Town Law & Order
      icon: cmd-home
    - name: grpNPCsTownMerchant
      uiName: Town Merchant
      icon: cmd-home
    - name: grpNPCsWild
      uiName: Wilderness
      icon: cmd-pine-tree

icon: cmd-reddit
attribution: |
  /r/BehindTheTables is a companion to /r/DnDBehindTheScreen, content is from multiple users and sources.
  <p>/u/OrkishBlade has done an incredible job curating a fun set of tables</p>
  <p><a href="https://www.reddit.com/r/BehindTheTables/comments/5ruebp/new_rules_for_behindthetables/">Re-Use rules for /r/BehindTheTables</a></p>
  <p><a href="https://www.reddit.com/r/BehindTheTables/wiki/index">/r/BehindTheTables Table of Tables</a></p>
  <blockquote>
  <p>Our tables are meant to supplement what's in the various editions of the DMG and PHB, cover
  ground that the tables in the books do not cover, or replace what's in the books for situations
  where it's cumbersome to flip through several tables in several locations within the book all at once.
  </p>
  <p>
  Our PRIMARY GOAL is to build a searchable, linked repository of tables for adding fun, flavor, and
  story to your D&D game.
  <br/>
  <br/>Our SECONDARY GOAL is to create a repository of these tables in the form of one-page
  printable cheat sheets for use at the gaming table free of laptop, tablet, and other electronic screens.
  </p>
  </blockquote>


