name: /r/BehindTheTables
id: behind_the_tables
priority: 200
url: https://www.reddit.com/r/BehindTheTables/
credit: /r/DnDBehindTheScreen
hasGroupHierarchy: true
groups:
  grpEncountersCastle: Encounters / Castle
  grpEncountersDungeon: Encounters / Dungeon
  grpEncountersTown: Encounters / Town
  grpEncountersWild: Encounters / Wilderness
  grpFactionsSettlement: Factions & Groups / Settlement
  grpFactionsWild: Factions & Groups / Wilderness
  grpLocationsCastle: Locations / Castle
  grpLocationsCavern: Locations / Cavern
  grpLocationsDungeon: Locations / Dungeon
  grpLocationsTown: Locations / Town
  grpLocationsWild: Locations / Wilderness
  grpNPCsAppPersMotiv: NPCs / Appearance, Motivations...
  grpNPCsCastle: NPCs / Castle
  grpNPCsCastleCourt: NPCs / Castle Court
  grpNPCsCastleDungeon: NPCs / Castle Dungeon
  grpNPCsCavern: NPCs / Cavern
  grpNPCsTown: NPCs / Town
  grpNPCsTownLaw: NPCs / Town Law & Order
  grpNPCsTownMerchant: NPCs / Town Merchant
  grpNPCsWild: NPCs / Wilderness

icon: cmd-reddit
groupIcons:
  Locations: cmd-map-marker
  Encounters: cmd-run
  Factions & Groups: cmd-account-multiple
  NPCs: cmd-account

  grpEncountersCastle: cmd-castle
  grpEncountersDungeon: cmd-cube-unfolded
  grpEncountersTown: cmd-home
  grpEncountersWild: cmd-pine-tree
  grpFactionsSettlement: cmd-home
  grpFactionsWild: cmd-pine-tree
  grpLocationsCastle: cmd-castle
  grpLocationsCavern: cmd-fire
  grpLocationsDungeon: cmd-cube-unfolded
  grpLocationsTown: cmd-home
  grpLocationsWild: cmd-pine-tree
  grpNPCsAppPersMotiv: cmd-face
  grpNPCsCastle: cmd-castle
  grpNPCsCastleCourt: cmd-castle
  grpNPCsCastleDungeon: cmd-castle
  grpNPCsCavern: cmd-fire
  grpNPCsTown: cmd-home
  grpNPCsTownLaw: cmd-home
  grpNPCsTownMerchant: cmd-home
  grpNPCsWild: cmd-pine-tree
attribution: |
  /r/BehindTheTables is a companion to /r/DnDBehindTheScreen, content is from multiple users and sources.
  <p>/u/OrkishBlade has done an incredible job organizing a fun set of tables</p>
  <blockquote>
  <p>Our tables are meant to supplement what's in the various editions of the DMG and PHB, cover
  ground that the tables in the books do not cover, or replace what's in the books for situations
  where it's cumbersome to flip through several tables in several locations within the book all at once.
  </p>
  <p>
  Our PRIMARY GOAL is to build a searchable, linked repository of tables for adding fun, flavor, and
  story to your D&D game.
  <br/>
  <br/>Our SECONDARY GOAL is to create a repository of these tables in the form of one-page
  printable cheat sheets for use at the gaming table free of laptop, tablet, and other electronic screens.
  </p>
  </blockquote>


