name: /r/BehindTheTables
url: https://www.reddit.com/r/BehindTheTables/
credit: /r/DnDBehindTheScreen
groups:
  - name: encounters
    uiName: Encounters
    icon: cmd-run
    groups:
    - name: grpEncountersCastle
      uiName: Castle
      icon: cmd-castle
    - name: grpEncountersDungeon
      uiName: Dungeon
      icon: cmd-cube-unfolded
    - name: grpEncountersTown
      uiName: Town
      icon: cmd-home
    - name: grpEncountersWild
      uiName: Wildnerness
      icon: cmd-pine-tree
  - name: factions
    uiName: Factions & Groups
    icon: cmd-account-multiple
    groups:
    - name: grpFactionsSettlement
      uiName: Settlement
      icon: cmd-home
    - name: grpFactionsWild
      uiName: Wilderness
      icon: cmd-pine-tree
  - name: locations
    uiName: Locations
    icon: cmd-map-marker
    groups:
    - name: grpLocationsCastle
      uiName: Castle
      icon: cmd-castle
    - name: grpLocationsCavern
      uiName: Cavern
      icon: cmd-fire
    - name: grpLocationsDungeon
      uiName: Dungeon
      icon: cmd-cube-unfolded
    - name: grpLocationsTown
      uiName: Town
      icon: cmd-home
    - name: grpLocationsWild
      uiName: Wilderness
      icon: cmd-pine-tree
  - name: npcs
    uiName: NPCs
    icon: cmd-account
    groups:
    - name: grpNPCsAppPersMotiv
      uiName: Appearance, Motivations...
      icon: cmd-face
    - name: grpNPCsCastle
      uiName: Castle
      icon: cmd-castle
    - name: grpNPCsCastleCourt
      uiName: Castle Court
      icon: cmd-castle
    - name: grpNPCsCastleDungeon
      uiName: Dungeon
      icon: cmd-castle
    - name: grpNPCsCavern
      uiName: Cavern
      icon: cmd-fire
    - name: grpNPCsTown
      uiName: Town
      icon: cmd-home
    - name: grpNPCsTownLaw
      uiName: Town Law & Order
      icon: cmd-home
    - name: grpNPCsTownMerchant
      uiName: Town Merchant
      icon: cmd-home
    - name: grpNPCsWild
      uiName: Wilderness
      icon: cmd-pine-tree

attribution: |
  /r/BehindTheTables is a companion to /r/DnDBehindTheScreen, content is from multiple users and sources.
  <p>/u/OrkishBlade has done an incredible job curating a fun set of tables</p>
  <p><a href="https://www.reddit.com/r/BehindTheTables/comments/5ruebp/new_rules_for_behindthetables/">Re-Use rules for /r/BehindTheTables</a></p>
  <p><a href="https://www.reddit.com/r/BehindTheTables/wiki/index">/r/BehindTheTables Table of Tables</a></p>
  <blockquote>
  <p>Our tables are meant to supplement what's in the various editions of the DMG and PHB, cover
  ground that the tables in the books do not cover, or replace what's in the books for situations
  where it's cumbersome to flip through several tables in several locations within the book all at once.
  </p>
  <p>
  Our PRIMARY GOAL is to build a searchable, linked repository of tables for adding fun, flavor, and
  story to your D&D game.
  <br/>
  <br/>Our SECONDARY GOAL is to create a repository of these tables in the form of one-page
  printable cheat sheets for use at the gaming table free of laptop, tablet, and other electronic screens.
  </p>
  </blockquote>


