name: GameMaster's Apprentice
credit: Larcenous Designs, LLC
url: "http://www.drivethrurpg.com/product/125685/The-GameMasters-Apprentice-Base-Deck"

attribution: |
  <a href="http://www.larcenousdesigns.com/">Larcenous Designs, LLC</a>
  <p><a href="http://www.drivethrurpg.com/product/125685/The-GameMasters-Apprentice-Base-Deck">GameMaster's Apprentice on DriveThruRPG</a></p>

  <p>The GameMaster’s Apprentice deck, copyright 2014, owned by Larcenous Designs, LLC and Nathan Rockwood.</p>

  <p>The text content in Adventuresmith from the <cite>GameMaster's Apprentice</cite> is from the GMA half-deck within
  <a href="http://www.drivethrurpg.com/product/168609/ALONe-A-Solo-Game-Engine-BETA">ALONe: A Solo Game Engine BETA</a>,
  released under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported  license.
  <br/>
  To see a copy of this license, go <a href="https://creativecommons.org/licenses/by-nc-sa/3.0/">here</a></p>
