name: Kaigaku
id: kaigaku
url: http://www.drivethrurpg.com/product/186267/Kaigaku-RPG
credit: Jacob DC Ross / Thunderegg Productions
icon: cmd-image-filter-vintage
attribution: |
  Copyright 2016, Thunderegg Productions
  <blockquote>
  <p>The Kaigaku RPG is a retroclone that blends simple OSR rules (by way of the Black Hack) and
  inspiration from famous samurai-themed games. You can use this book to play intense duels between
  bushi, wars of words among courtiers, ninja missions and more.</p>
  </blockquote>




