name: "Coriolis"
credit: Fria Ligan
url: "http://frialigan.se/en/games/coriolis/"

groups:
- name: characters
  uiName: Characters
  icon: cmd-account-multiple
- name: adv_seeds
  uiName: Adventure Seeds
  icon: cmd_rocket
- name: sys_gen
  uiName: System Generators
  icon: cmd_chart_bubble
attribution: |
  <p>
  <a href="http://www.drivethrurpg.com/product/204291/Coriolis--The-Third-Horizon-core-book">Coriolis: The Third Horizon core book on DriveThruRPG</a>
  </p>
  <p>
  <a href="http://www.drivethrurpg.com/product/204292/Coriolis-Atlas-Compendium">Coriolis Atlas Compendium on DrivethruRPG </a>
  </p>
  <p>
  <a href="http://frialigan.se/en/games/coriolis/">Coriolis on Fria Ligan's Site</a>
  </p>
  <p>
  <a href="http://freeleaguepublishing.com/">Free League Publishing</a>
  </p>
  <p>
  CORIOLIS © - 2017 Paradox Interactive AB. CORIOLIS is a trademark of Paradox Interactive AB. Used with permission from Paradox Interactive AB.
  All rights reserved. <a href="http://www.paradoxplaza.com">www.paradoxplaza.com</a>
  </p>
  <p>The content in Adventuresmith is from the <cite>Coriolis: The Third Horizon</cite> corebook and <cite>Coriolis Atlas Compendium</cite></p>