name: Freebooters on the Frontier
id: freebooters_on_the_frontier
credit: Jason Lutes
priority: 200
url: "http://lampblackandbrimstone.blogspot.com/"
attribution: |
  <p>Written by <strong>Jason Lutes</strong> in Hartland, Vermont, U.S.A.</p>
  <p>The content of Freebooters on the Frontier relies upon the rules contained in <em>Dungeon World</em>,
  by <strong>Adam Koebel</strong> and <strong>Sage LaTorra</strong>, licensed under a Creative Commons Attribution 3.0 Unported license.</p>
  <p>The text of <em>Freebooters on the Frontier</em> is released under a Creative Commons Attribution - ShareAlike 3.0 Unported license.</p>
  <p><strong>Antoine Pempie</strong> - French translation of Freebooters on the Frontier, released under Creative Commons Attribution - ShareAlike 3.0 Unported license.﻿</p>
