name: Knave
credit: Ben Milton
url: "http://questingblog.com/"

attribution: |
  Created by <strong>Ben Milton</strong>, or "Questing Beast" on YouTube.
  <p>Knave was made possible due to the encouragement, feedback, and assistance of
  <a href="https://www.patreon.com/questingbeast">Ben Milton's Patreon supporters</a>.</p>
  <p><a href="https://www.drivethrurpg.com/product/250888/Knave">Knave on DriveThruRPG</a></p>
  <p>The text of <em>Knave</em> is released under a CC Attribution 4.0 International License
  https://creativecommons.org/licenses/by/4.0/</p>
  <p>Names for chargen are copied from Ben Milton's Maze Rats</p>
