name: Dice Roller
id: dice_roller
priority: 999
icon: cmd-dice-6
groupIcons:
  grpPolys: cmd-dice-1
  grpCombinations: cmd-dice-2
  grpCustom: cmd-dice-3
  grpFudge: cmd-plus-box
  grpEOTE: cmd-scale-balance     # cmd-sync , cmd-theme-light-dark
groups:
  grpPolys: Single Polyhedral
  grpCombinations: Common Combos
  grpCustom: Custom Dice
  grpFudge: Fudge & Exploding
  grpEOTE: EotE

