name: Dice Roller

groups:
- name: grpPolys
  uiName: Single Polyhedral
  icon: cmd-dice-1
- name: grpCombinations
  uiName: Common Combos
  icon: cmd-dice-2
- name: grpCustom
  uiName: Custom Dice
  icon: cmd-multiplication-box
- name: grpFudge
  uiName: Fudge & Exploding
  icon: cmd-plus-box
- name: grpEOTE
  uiName: EotE Dice
  icon: cmd-theme-light-dark
