name: Dice Roller
id: dice_roller
priority: 999
icon: cmd-dice-6
groupIcons:
  grpPolys: cmd-dice-1
  grpCombinations: cmd-dice-2
  grpCustom: cmd-dice-3
groups:
  grpPolys: Std Polyhedral
  grpCombinations: Common Combos
  grpCustom: Custom Dice

