name: "Mutant: Year Zero"
credit: Fria Ligan
url: "http://frialigan.se/en/games/mutant-year-zero/"

groups:
- name: ark
  uiName: The Ark
  icon: cmd_domain #cmd_home #cmd_home_map_marker #cmd_gate
- name: zone
  uiName: The Zone
  icon: cmd-biohazard
- name: gla
  uiName: Genlab Alpha
  icon: cmd-test-tube
attribution: |
  <p>
  <a href="http://www.drivethrurpg.com/product/139453/MUTANT-Year-Zero--Roleplaying-At-The-End-Of-Days">Mutant: Year Zero on DrivethruRPG</a>
  </p>
  <p>
  <a href="http://frialigan.se/en/games/mutant-year-zero/">Mutant: Year Zero on Fria Ligan's Site</a>
  </p>
  <p>
  <a href="http://freeleaguepublishing.com/">Free League Publishing</a>
  </p>
  <p>
  © 2017 Game Ark Limited, part of the Cabinet Group. MUTANT and related logos, characters, names,
  and distinctive likenesses thereof are trademarks or registered trademarks of Game Ark Limited.
  Used with permission. All rights reserved.
  </p>
  <p>The content in Adventuresmith is from the <cite>Mutant: Year Zero</cite> and  <cite>Mutant: Genlab Alpha</cite> corebooks</p>
