name: Maze Rats
id: maze_rats
credit: Ben Milton
url: "http://questingblog.com/maze-rats/"
groups:
  grpChar: Characters & NPCs
  grpCity: The City
  grpWild: The Wild
  grpMaze: The Maze
  grpItems: Treasure & Equipment
  grpMisc: Other...
  grpZZ: Maze Rats 0.1
icon: cmd-cube-unfolded
groupIcons:
  grpChar: ion-android-people
  grpCity: cmd-castle
  grpWild: cmd-pine-tree
  grpMaze: cmd-view-dashboard
  grpItems: cmd-diamond
  grpMisc: cmd-dice-d20
  grpZZ: cmd-cube-unfolded
attribution: |
  Created by <strong>Ben Milton</strong>, or "Questing Beast" on YouTube.
  <p>Maze Rats is PWYW, and available here http://www.drivethrurpg.com/product/197158/Maze-Rats</p>
  <p>The text of <em>Maze Rats 4.1</em> is released under a CC BY 4.0 license
  https://creativecommons.org/licenses/by/4.0/</p>
  <p>Spanish translation by: <strong>Séregras</strong>. Available here http://questingblog.com/downloads/</p>
