name: Maze Rats
credit: Ben Milton
url: "http://questingblog.com/maze-rats/"

groups:
  - name: grpChar
    uiName: Characters & NPCs
    icon: cmd-account-multiple
  - name: grpCity
    uiName: The City
    icon: cmd-castle
  - name: grpWild
    uiName: The Wild
    icon: cmd-pine-tree
  - name: grpMaze
    uiName: The Maze
    icon: cmd-view-dashboard
  - name: grpItems
    uiName: Treasure & Equipment
    icon: cmd-diamond
  - name: grpMisc
    uiName: Other...
    icon: cmd-dice-d20
  - name: grpZZ
    uiName: Maze Rats 0.1
    icon: cmd-cube-unfolded

attribution: |
  Created by <strong>Ben Milton</strong>, or "Questing Beast" on YouTube.
  <p><a href="http://www.drivethrurpg.com/product/197158/Maze-Rats">Maze Rats on DriveThruRPG</a></p>
  <p>The text of <em>Maze Rats 4.1</em> is released under a CC BY 4.0 license
  https://creativecommons.org/licenses/by/4.0/</p>
  <p>Spanish translation by: <strong>Séregras</strong>. Available here <a href="http://questingblog.com/downloads/">http://questingblog.com/downloads/</a></p>
