name: Stars Without Number
credit: Kevin Crawford / Sine Nomine Publishing
url: "http://www.sinenomine-pub.com/"
attribution: |
  <p><a href="http://www.drivethrurpg.com/product/94621/Stars-Without-Number%3A-Core-Edition">Stars Without Number on DriveThruRPG</a></p>

  <p><a href="http://www.drivethrurpg.com/browse/pub/3482/Sine-Nomine-Publishing">Sine Nomine Publishing on DriveThruRPG</a></p>
  <p>The content reproduced here is from the free version of the core SWN rulebook and various free supplements.</p>
  <blockquote>
  <p>Stars Without Number is a retro science fiction role playing game influenced by the Old School
  Renaissance and partially inspired by the great fantasy role-playing game editions written by
  Tom Moldvay and Frank Mentzer. The contents are compatible with most old school clones and are
  designed to be easily imported to your own favorite gaming system. In addition to a complete
  pre-made stellar sector, Stars Without Number offers GMs and players the tools to create their
  own sandbox-style adventures in the far future.</p>
  </blockquote>

groups:
- name: aaw
  uiName: Aliens, Animals, Worlds…
  icon: ion-planet
- name: cr
  uiName: Corps, Religions…
  icon: ion-person-stalker
- name: names
  uiName: Names
  icon: ion-edit
- name: tech_arch
  uiName: Tech, Architecture…
  icon: cmd-factory
- name: chars_npcs
  uiName: Characters, NPCs…
  icon: ion-person
