name: Stars Without Number
id: stars_without_number
credit: Kevin Crawford / Sine Nomine Publishing
url: "http://www.sinenomine-pub.com/"
attribution: |
  <p><a href="http://www.drivethrurpg.com/product/94621/Stars-Without-Number%3A-Core-Edition">Stars Without Number on DriveThruRPG</a></p>

  <p><a href="http://www.drivethrurpg.com/browse/pub/3482/Sine-Nomine-Publishing">Sine Nomine Publishing on DriveThruRPG</a></p>
  The content reproduced here is from the free version of the core SWN rulebook and various free supplements.
  <blockquote>
  <p>Stars Without Number is a retro science fiction role playing game influenced by the Old School
  Renaissance and partially inspired by the great fantasy role-playing game editions written by
  Tom Moldvay and Frank Mentzer. The contents are compatible with most old school clones and are
  designed to be easily imported to your own favorite gaming system. In addition to a complete
  pre-made stellar sector, Stars Without Number offers GMs and players the tools to create their
  own sandbox-style adventures in the far future.</p>
  <blockquote>
icon: cmd-rocket
groupIcons:
  grp1: ion-planet
  grp2: ion-person-stalker
  grp3: ion-edit
  grp4: cmd-factory
  grp5: ion-person
groups:
  grp1: Aliens, Animals, Worlds…
  grp2: Corps, Religions…
  grp3: Names
  grp4: Tech, Architecture…
  grp5: Characters, NPCs…
