name: Augmented Reality
id: augmented_reality
url: http://www.drivethrurpg.com/product/202175/Augmented-Reality-The-Holistic-City-Kit-For-Cyberpunk-Games
credit: Paul D. Gallagher / Geist Hack Games
attribution: |
  <cite>Augmented Reality</cite> was designed and compiled by <strong>Paul D. Gallagher</strong>.
  <br/><a href="http://neuralarchive.blogspot.co.uk">Geist's blog</a>
  <p>© Geist Hack Games 2017</p>
  <p><a href="http://www.drivethrurpg.com/product/202175/Augmented-Reality-The-Holistic-City-Kit-For-Cyberpunk-Games">Augmented Reality on DriveThruPRG</a></p>

  <blockquote>
  Style And Substance: Enhance your games of the dark future, with the easy to use Augmented Reality
  cyberpunk city kit. Inside, you’ll find over 50 tables designed to assist gamesmasters who need to
  improvise futuristic city details, or who have found that they are unprepared for where their players are heading.
  <p>With this book, you can add layers of detail to any cyberpunk cityscape, and make use of over
  250 NPCs, including fixers, street samurai, corporate players and insane hackers, along with easy
  to roll cabbies, cops, gang members and street fighters. Missions, motivations and methods can be
  generated, along with the immediate urban environment, all painted with a broad brush, to enable
  gamesmasters to let their twisted imaginations shine through, without slowing down the action.</p>
  </blockquote>
icon: cmd-nfc-variant

groupedGenerators:
  grpNPCs:
  - cabbies
  - corporate_aristocrats
  - covert_go_between
  - fixers
  - gangs
  - guns_for_hire
  - hackers
  - instacitizen
  - street_walkers
  - tattoo
  - vices
  grpSenses:
  - augmented_reality
  - infotainment
  - quirky_interiors
  - sights
  - smells
  - sounds
  - vehicle_river
  - vehicle_road
  - vehicle_sky
  - weather
  grpEncounters:
  - bio_horrors
  - first_contact
  - freak_fighters
  - gigs
  - jobs
  - ops
  - trespass
  grpCity:
  - alternative_business
  - area_events
  - downtown
  - hackable_assets
  - legacy_data
  - legacy_infrastructure
  - local_conflict
  - nightlife
  - street_uses
  grpCorps:
  - boardroom_manoeuvers #0
  - company_resources #0
  - backup
  - department
  - first_responders
  - job_sheet
  - response_level
  grpLoot:
  - condition
  - one_mans_trash
  - vendomat
  - whats_on_corpse
  - whats_on_thing
  - where_has_it_been

groups:
  - name: grpNPCs
    uiName: NPCs
    icon: cmd_account_multiple
  - name: grpSenses
    uiName: Sense & the City
    icon: cmd_eye
  - name: grpEncounters
    uiName: Encounters & Jobs
    icon: cmd_human_greeting
  - name: grpCity
    uiName: Buildings & Assets
    icon: cmd_city
  - name: grpCorps
    uiName: Corps & Cops
    icon: cmd_factory
  - name: grpLoot
    uiName: Technology & Items
    icon: cmd_cash