name: Augmented Reality
id: augmented_reality
priority: 100
url: http://www.drivethrurpg.com/product/202175/Augmented-Reality-The-Holistic-City-Kit-For-Cyberpunk-Games
credit: Paul D. Gallagher / Geist Hack Games
attribution: |
  <cite>Augmented Reality</cite> was designed and compiled by <strong>Paul D. Gallagher</strong>. (Geist at at http://neuralarchive.blogspot.co.uk)
  <p>© Geist Hack Games 2017</p>

  <blockquote>
  Style And Substance: Enhance your games of the dark future, with the easy to use Augmented Reality
  cyberpunk city kit. Inside, you’ll find over 50 tables designed to assist gamesmasters who need to
  improvise futuristic city details, or who have found that they are unprepared for where their players are heading.
  <p>With this book, you can add layers of detail to any cyberpunk cityscape, and make use of over
  250 NPCs, including fixers, street samurai, corporate players and insane hackers, along with easy
  to roll cabbies, cops, gang members and street fighters. Missions, motivations and methods can be
  generated, along with the immediate urban environment, all painted with a broad brush, to enable
  gamesmasters to let their twisted imaginations shine through, without slowing down the action.</p>
  </blockquote>
groups:
  grpCity: City


