name: Hack & Slash
id: hack_and_slash
credit: Courtney C. Campbell
url: "http://hackslashmaster.blogspot.com/"
icon: cmd-sword
generators:
  - doors #100
  - empty_rooms #100
  - magic_pools #100
  - traps #100
  - contents_of_pit
  - corridors
  - curses
  - things
  - tricks
  - wfc
attribution: |
  <h5>Tricks, Empty Rooms, & Basic Trap Design</h5>
  All text is © Courtney C. Campbell (2011).
  <br/>
  <br/><a href="http://hackslashmaster.blogspot.com/2011/02/on-tricks-empty-rooms-and-basic-trap.html">Tricks, Empty Rooms, & Basic Trap Design</a>



